### PR TITLE
Visualize-multiple-histogram-and-density-plots

### LINKED ISSUE #33: Multiple distribution histograms and density plots
**Topics to cover:** Multiple distribution histogram and density plot

**Link to WIP blog post:**  https://docs.google.com/document/d/1WF2mB_NKIDymBIi8TfHXtPsAAH_3CNKDh0sgjA649Ls/edit

**Checklist:**

Tasks:

- [x] Notebook created
- [x] Blog post created
- [x] Notebook rendered on GitHub pages
- [ ] Blog post published
- [ ] Social media announcements

Checks:

- [x] Is the notebook reproducible
- [x] Does the notebook text and blog post text follow our docs style guide
- [x] Do all images have alt-text?

### PR DESCRIPTION
**Pull request by Azaya89**
fixes #33 

**Tasks:**
- [x] finished the multiple histogram notebook

**Edit**
commit `92ae473` uses `varea()` glyph for the density estimates but the `line_color` parameter throws an error message so I commented it out. I don't know if that's a bug.

### CODE REVIEW

**Review by pavithraes — APPROVED** [review]

**Comment by Azaya89** [comment]
Here's the full Traceback when I run the notebook without commenting out the `line_color` parameter when using the `varea()` glyph:

```AttributeError                            Traceback (most recent call last)
Cell In[10], line 34
     31 kde = KernelDensity(kernel="gaussian", bandwidth=bandwidth).fit(data[:, np.newaxis])
     32 log_dens = kde.score_samples(positions[:, np.newaxis])
---> 34 p.varea(
     35     x=positions,
     36     y1=np.exp(log_dens),
     37     y2=0,
     38     fill_alpha=0.3,
     39     fill_color=color,
     40     line_color=color,
     41 )
     43 # Find the highest point and annotate with the label
     44 max_idx = np.argmax(np.exp(log_dens))

File ~\anaconda3\lib\site-packages\bokeh\plotting\_decorators.py:87, in glyph_method.<locals>.decorator.<locals>.wrapped(self, *args, **kwargs)
     85 if self.coordinates is not None:
     86     kwargs.setdefault("coordinates", self.coordinates)
---> 87 return create_renderer(glyphclass, self.plot, **kwargs)

File ~\anaconda3\lib\site-packages\bokeh\plotting\_renderer.py:113, in create_renderer(glyphclass, plot, **kwargs)
    110 # handle the mute glyph, we always set one
    111 muted_visuals = pop_visuals(glyphclass, kwargs, prefix='muted_', defaults=glyph_visuals, override_defaults={'alpha':0.2})
--> 113 glyph = make_glyph(glyphclass, kwargs, glyph_visuals)
    114 nonselection_glyph = make_glyph(glyphclass, kwargs, nonselection_visuals)
    115 selection_glyph = make_glyph(glyphclass, kwargs, selection_visuals)

File ~\anaconda3\lib\site-packages\bokeh\plotting\_renderer.py:142, in make_glyph(glyphclass, kws, extra)
    140 kws = kws.copy()
    141 kws.update(extra)
--> 142 return glyphclass(**kws)

File ~\anaconda3\lib\site-packages\bokeh\models\glyphs.py:1517, in VArea.__init__(self, *args, **kwargs)
   1516 def __init__(self, *args, **kwargs) -> None:
-> 1517     super().__init__(*args, **kwargs)

File ~\anaconda3\lib\site-packages\bokeh\models\glyph.py:111, in FillGlyph.__init__(self, *args, **kwargs)
    110 def __init__(self, *args, **kwargs) -> None:
--> 111     super().__init__(*args, **kwargs)

File ~\anaconda3\lib\site-packages\bokeh\models\glyph.py:131, in HatchGlyph.__init__(self, *args, **kwargs)
    130 def __init__(self, *args, **kwargs) -> None:
--> 131     super().__init__(*args, **kwargs)

File ~\anaconda3\lib\site-packages\bokeh\models\glyph.py:58, in Glyph.__init__(self, *args, **kwargs)
     57 def __init__(self, *args, **kwargs) -> None:
---> 58     super().__init__(*args, **kwargs)

File ~\anaconda3\lib\site-packages\bokeh\model\model.py:110, in Model.__init__(self, *args, **kwargs)
    107 if "id" in kwargs:
    108     raise ValueError("initializing 'id' is not allowed")
--> 110 super().__init__(**kwargs)
    111 default_theme.apply_to_model(self)

File ~\anaconda3\lib\site-packages\bokeh\core\has_props.py:298, in HasProps.__init__(self, **properties)
    296     if value is Undefined or value is Intrinsic:
    297         continue
--> 298     setattr(self, name, value)
    300 for name in self.properties() - set(properties.keys()):
    301     desc = self.lookup(name)

File ~\anaconda3\lib\site-packages\bokeh\core\has_props.py:333, in HasProps.__setattr__(self, name, value)
    330 if isinstance(descriptor, property): # Python property
    331     return super().__setattr__(name, value)
--> 333 self._raise_attribute_error_with_matches(name, properties)

File ~\anaconda3\lib\site-packages\bokeh\core\has_props.py:368, in HasProps._raise_attribute_error_with_matches(self, name, properties)
    365 if not matches:
    366     matches, text = sorted(properties), "possible"
--> 368 raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")

AttributeError: unexpected attribute 'line_color' to VArea, similar attributes are fill_color

**Comment by bryevdv** [comment]
@Azaya89 This error is expected, since `varea` does not have line properties. That is because a main use case of varea is to have stacked areas, and if `varea` had an "outline" then part of the outline for two areas (one above and one below) would completely overlap on the screen. Even with a single, non-stacked area, usually for directed areas you only want a line on one side (e.g. the "top") and for this you can use a separate `line`

**Comment by Azaya89** [comment]
> @Azaya89 This error is expected, since `varea` does not have line properties. That is because a main use case of varea is to have stacked areas, and if `varea` had an "outline" then part of the outline for two areas (one above and one below) would completely overlap on the screen. Even with a single, non-stacked area, usually for directed areas you only want a line on one side (e.g. the "top") and for this you can use a separate `line`

OK. I guess this makes sense. My confusion stemmed from looking at the docstring for the `varea()` glyph and seeing this part:

> Other Parameters:
>     ...
> 
>     color (color, optional) :
>         An alias to set all color keyword arguments at once. (default: None)
> 
>         See :ref:`ug_styling_colors` in the user guide for different
>         options to define colors.
> 
>         Any explicitly set values for ``line_color``, etc. will override this
>         setting.
> 

It gave me the idea that `line_color` is also a valid parameter.

**Comment by bryevdv** [comment]
Ah, yes that's  a corner case that is misleading could be improved. `color` is a parameter and description that gets added all glyphs, because it's actually true for almost all of them. We'd need to make a way to selectively add that only to the glyphs it applies to in order to improve.

**Comment by Azaya89** [comment]
@bryevdv  I think this is ready for merging now?

**Pull request merged**
