### PR TITLE
Single distribution histogram

### LINKED ISSUE #29: Single distribution histogram and density plot
**Topics to cover:** Single distribution histogram and density plot

**Link to WIP blog post:**  https://docs.google.com/document/d/1awwo3u5jDmOQ2tN9ftr1BXpJiaAzOpx-W0yT8c2mgs8/edit

**Checklist:**

Tasks:

- [x] Notebook created
- [x] Blog post created
- [x] Notebook rendered on GitHub pages
- [x] Blog post published
- [x] Social media announcements

Checks:

- [x] Is the notebook reproducible
- [x] Does the notebook text and blog post text follow our docs style guide
- [x] Do all images have alt-text?

### PR DESCRIPTION
**Pull request by Azaya89**
fixes #29 

**Tasks:**
- [x] created the single histogram plot and gridplot
- [x] added the histogram images to the `images` directory
- [x] created single density plot and gridplot
- [x] added density plot images to `images` directory

### CODE REVIEW

**Review by bryevdv — COMMENTED** [review]
"check out user guide" link for quad is currently linking to the reference guide, not the user guide

**Review by bryevdv — COMMENTED** [review]
extra capitalization typo near bottom: "TItanic"

**Comment by bryevdv** [comment]
Hi @Azaya89 I have not had a chance to run the code, but glancing a comparison at the book, the plots in the KDE grid look to be a little different:

* missing x-axis label "age (years)" on a) and b) 
* lower "resolution"? The book plots appear to have finer detail along the x-axis  especially plots a) and d)

Also a) and c) in the histogram grid look a bit different from Fig 7.2 is this a slightly different binning perhaps? Ideally we find a way to match exactly but if we can't get numpy to match the R results exactly we could at least make a small comment acknowledging the difference as expected.

**Comment by Azaya89** [comment]
> Hi @Azaya89 I have not had a chance to run the code, but glancing a comparison at the book, the plots in the KDE grid look to be a little different:
> 
> * missing x-axis label "age (years)" on a) and b)
> * lower "resolution"? The book plots appear to have finer detail along the x-axis  especially plots a) and d)
> 

The images are different because of the way they were saved from the notebook. If the code is run, the x-axis labels all show up but when I try to save them, it appears this way. This is something I had noticed from the first time I tried saving the bar plots displayed in a grid format. Then, I simply screenshot the image instead of saving it using the `save` tool in the plots. This time I couldn't screenshot the gridplot because they don't all display as a static image but rather as scrollable images.

Here's what I mean:
1. The histogram gridplot is easy to screenshot since the `save` tool will not save it properly
b1906f7f-3438-4aa8-b542-5ca2670bd446

2. The density gridplot cannot be screenshot in its entirety and the `save` tool will not save it correctly either.

efafc131-592c-4e0f-bacd-7c08ec5e6933

**Comment by Azaya89** [comment]
> Also a) and c) in the histogram grid look a bit different from Fig 7.2 is this a slightly different binning perhaps? Ideally we find a way to match exactly but if we can't get numpy to match the R results exactly we could at least make a small comment acknowledging the difference as expected.

I actually don't see how the histogram grid is much different from that of the book plots, although I noticed that the underlying data is slightly different from what was presented in the book. The actual figures from the `titanic_all` file is not exactly the same as what is displayed in the book. I think that is the reason why the bars are not exactly identical.

**Comment by Azaya89** [comment]
I have replaced the grid-density image with a better one gotten via `export_png()`.

**Review by bryevdv — APPROVED** [review]

**Review by pavithraes — APPROVED** [review]

**Pull request merged**
