### PR TITLE
Introduction files

### LINKED ISSUE #22: Introduction files
The `Introduction.ipynb` and `Introduction.html` files till contain the old file paths. I have to modify them to refelct the new file paths and also reflect the style guide for subsequent posts.

### PR DESCRIPTION
**Pull request by Azaya89**
fixes #22 

**Task:**
- [x] Modifies `Introduction.ipynb` and `Introduction.html` files to reflect new style and file paths

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]
LGTM but I would still suggest manually clearing all the output cells in the notebook and committing the un-executed version before merging.

**Comment by Azaya89** [comment]
> LGTM but I would still suggest manually clearing all the output cells in the notebook and committing the un-executed version before merging.

Alright. Noted

**Comment by Azaya89** [comment]
> LGTM but I would still suggest manually clearing all the output cells in the notebook and committing the un-executed version before merging.

My apologies, I need some more clarification here. If I commit the un-executed version of the notebook, will the output still be available to view on `ReviewNB` ? 
Or did you mean that **after**  all the reviews, I should clear the output cells before merging the PR?

**Comment by bryevdv** [comment]
@Azaya89 the output will not be visible if it is cleared, but, at least IMO, almost of the review work involves input cells, which will be visible regardless.

**Pull request merged**
