### PR TITLE
Moved convert_to_csv to scripts directory

### PR DESCRIPTION
**Pull request by Azaya89**
**Solves:**  Issue #15 
**Tasks:**
- [x] created `scripts` directory
- [x] moved `convert_to_csv.py` from `rda_files` to `scripts` directory
- [x] deleted 'errors.txt` file

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]
LGTM!

**Comment by Azaya89** [comment]
@bryevdv  Can we merge this now?

**Comment by bryevdv** [comment]
@Azaya89 sorry I thought you could merge. I really prefer a "review -> self-merge" process so I'll sort out the repo permissions today.

**Comment by Azaya89** [comment]
I can actually merge. I just didn't think I should do the merging :)

**Pull request merged**
